# Generated by Django 3.0 on 2020-09-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassabiz', '0002_auto_20200909_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
