# Generated by Django 3.0 on 2020-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassabiz', '0003_auto_20200912_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
