# Generated by Django 3.0 on 2020-09-16 09:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassabiz', '0005_auto_20200913_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_title', models.CharField(max_length=200)),
                ('press_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('press_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
