# Generated by Django 3.0 on 2020-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassabiz', '0006_pressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressmodel',
            name='press_body',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
